// this file is include!'d from both sandbox.rs and build.rs.
// fields may be unused in one context but used in the other.

/// source type for a VFS module entry
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(dead_code)]
enum VfsSource {
    /// .sld/.scm files embedded at build time
    Embedded,
    /// registered at runtime via #[tein_module] — no files to embed
    Dynamic,
    /// shadow module — .sld injected into dynamic VFS at sandbox build time only.
    /// unsandboxed contexts use chibi's native version.
    Shadow,
}

/// C static library backing for a module
#[derive(Clone, Copy, Debug)]
#[allow(dead_code)]
struct ClibEntry {
    /// C source file relative to chibi dir
    source: &'static str,
    /// init function suffix for the static lib table
    init_suffix: &'static str,
    /// VFS key for static lib lookup
    vfs_key: &'static str,
    /// requires POSIX headers (`<sys/time.h>`, `<poll.h>`, `<unistd.h>`);
    /// excluded from compilation and the static library table on windows targets
    posix_only: bool,
}

/// a single module in the VFS registry
#[derive(Clone, Debug)]
#[allow(dead_code)]
struct VfsEntry {
    /// module path, e.g. "scheme/char", "srfi/1"
    path: &'static str,
    /// transitive module deps (resolved at builder time)
    deps: &'static [&'static str],
    /// files to embed relative to chibi lib/
    files: &'static [&'static str],
    /// C static library, if native-backed
    clib: Option<ClibEntry>,
    /// in the default safe set?
    default_safe: bool,
    /// embedded or runtime-registered
    source: VfsSource,
    /// required cargo feature (None = always)
    feature: Option<&'static str>,
    /// shadow .sld content — only used when source is `Shadow`.
    /// injected into dynamic VFS by `register_vfs_shadows()` in sandboxed contexts.
    shadow_sld: Option<&'static str>,
}

/// full VFS module registry — single source of truth for all VFS modules.
///
/// bootstrap files (`init-7.scm`, `meta-7.scm`) are NOT in this registry —
/// they are handled separately in build.rs as they are not importable modules.
///
/// `(chibi)` primitive core is never listed as a dep — always available, not gated.
const VFS_REGISTRY: &[VfsEntry] = &[
    // -------------------------------------------------------------------------
    // tein modules
    // -------------------------------------------------------------------------
    VfsEntry {
        path: "tein/foreign",
        deps: &["scheme/base"],
        files: &["lib/tein/foreign.sld", "lib/tein/foreign.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/reader",
        deps: &["scheme/base"],
        files: &["lib/tein/reader.sld", "lib/tein/reader.scm"],
        clib: Some(ClibEntry {
            source: "lib/tein/reader.c",
            init_suffix: "tein_reader",
            vfs_key: "/vfs/lib/tein/reader",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/macro",
        deps: &["scheme/base"],
        files: &["lib/tein/macro.sld", "lib/tein/macro.scm"],
        clib: Some(ClibEntry {
            source: "lib/tein/macro.c",
            init_suffix: "tein_macro",
            vfs_key: "/vfs/lib/tein/macro",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/test",
        deps: &["scheme/base", "scheme/write"],
        files: &["lib/tein/test.sld", "lib/tein/test.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/docs",
        deps: &["scheme/base"],
        files: &["lib/tein/docs.sld", "lib/tein/docs.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/json",
        deps: &["scheme/base"],
        files: &["lib/tein/json.sld", "lib/tein/json.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: Some("json"),
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/toml",
        deps: &["scheme/base"],
        files: &["lib/tein/toml.sld", "lib/tein/toml.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: Some("toml"),
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/uuid",
        deps: &[],
        files: &[],
        clib: None,
        default_safe: true,
        source: VfsSource::Dynamic,
        feature: Some("uuid"),
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/time",
        deps: &[],
        files: &[],
        clib: None,
        default_safe: true,
        source: VfsSource::Dynamic,
        feature: Some("time"),
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/file",
        deps: &["scheme/base"],
        files: &["lib/tein/file.sld", "lib/tein/file.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "tein/load",
        deps: &["scheme/base"],
        files: &["lib/tein/load.sld", "lib/tein/load.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // tein/process: safe — trampolines neuter env vars, command-line, in sandbox
    VfsEntry {
        path: "tein/process",
        deps: &["scheme/base"],
        files: &["lib/tein/process.sld", "lib/tein/process.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // -------------------------------------------------------------------------
    // r7rs standard libraries (safe subset)
    // -------------------------------------------------------------------------
    VfsEntry {
        path: "scheme/base",
        deps: &[
            "chibi/equiv",
            "chibi/string",
            "chibi/io",
            "chibi/ast",
            "srfi/9",
            "srfi/11",
            "srfi/39",
        ],
        files: &[
            "lib/scheme/base.sld",
            "lib/scheme/define-values.scm",
            "lib/scheme/extras.scm",
            "lib/scheme/misc-macros.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/bitwise",
        deps: &["srfi/151"],
        files: &["lib/scheme/bitwise.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/box",
        deps: &["srfi/111"],
        files: &["lib/scheme/box.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/bytevector",
        deps: &["scheme/base", "srfi/151"],
        files: &["lib/scheme/bytevector.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/case-lambda",
        deps: &["srfi/16"],
        files: &["lib/scheme/case-lambda.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/char",
        deps: &[
            "scheme/base",
            "chibi/char-set/full",
            "chibi/char-set/base",
            "chibi/iset/base",
        ],
        files: &[
            "lib/scheme/char.sld",
            "lib/scheme/char/full.scm",
            "lib/scheme/char/special-casing.scm",
            "lib/scheme/char/case-offsets.scm",
            "lib/scheme/char/ascii.scm",
            "lib/scheme/digit-value.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/charset",
        deps: &["srfi/14"],
        files: &["lib/scheme/charset.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/comparator",
        deps: &["srfi/128"],
        files: &["lib/scheme/comparator.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/complex",
        deps: &[],
        files: &["lib/scheme/complex.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/cxr",
        deps: &[],
        files: &["lib/scheme/cxr.sld", "lib/scheme/cxr.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/division",
        deps: &["scheme/base"],
        files: &["lib/scheme/division.sld", "lib/scheme/division.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/ephemeron",
        deps: &["srfi/124"],
        files: &["lib/scheme/ephemeron.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // scheme/eval: default_safe: false — exports eval + environment
    VfsEntry {
        path: "scheme/eval",
        deps: &[],
        files: &["lib/scheme/eval.sld"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/fixnum",
        deps: &["srfi/143"],
        files: &["lib/scheme/fixnum.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/flonum",
        deps: &["srfi/144"],
        files: &["lib/scheme/flonum.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/generator",
        deps: &["srfi/121"],
        files: &["lib/scheme/generator.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/hash-table",
        deps: &["srfi/125"],
        files: &["lib/scheme/hash-table.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/ideque",
        deps: &["srfi/134"],
        files: &["lib/scheme/ideque.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/ilist",
        deps: &["srfi/116"],
        files: &["lib/scheme/ilist.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/inexact",
        deps: &[],
        files: &["lib/scheme/inexact.sld", "lib/scheme/inexact.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/lazy",
        deps: &[],
        files: &["lib/scheme/lazy.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/list",
        deps: &["srfi/1"],
        files: &["lib/scheme/list.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/list-queue",
        deps: &["srfi/117"],
        files: &["lib/scheme/list-queue.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/lseq",
        deps: &["srfi/127"],
        files: &["lib/scheme/lseq.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/mapping",
        deps: &["srfi/146"],
        files: &["lib/scheme/mapping.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/read",
        deps: &["srfi/38"],
        files: &["lib/scheme/read.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/regex",
        deps: &["srfi/115"],
        files: &["lib/scheme/regex.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // scheme/repl: default_safe: false — exports interaction-environment
    VfsEntry {
        path: "scheme/repl",
        deps: &[],
        files: &["lib/scheme/repl.sld"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/rlist",
        deps: &["srfi/101"],
        files: &["lib/scheme/rlist.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/set",
        deps: &["srfi/113"],
        files: &["lib/scheme/set.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/sort",
        deps: &["srfi/132"],
        files: &["lib/scheme/sort.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/stream",
        deps: &["srfi/41"],
        files: &["lib/scheme/stream.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/text",
        deps: &["srfi/135"],
        files: &["lib/scheme/text.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/vector",
        deps: &["srfi/133"],
        files: &["lib/scheme/vector.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/write",
        deps: &["srfi/38"],
        files: &["lib/scheme/write.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // scheme/file: VFS shadow — sandboxed contexts re-export from (tein file).
    // policy enforcement for open-*-file is at the C opcode level (eval.c patches F, G).
    // unsandboxed contexts use chibi's native scheme/file directly.
    VfsEntry {
        path: "scheme/file",
        deps: &["tein/file"],
        files: &[],
        clib: None,
        default_safe: true,
        source: VfsSource::Shadow,
        feature: None,
        shadow_sld: Some("\
(define-library (scheme file)
  (import (tein file))
  (export file-exists? delete-file
          open-input-file open-binary-input-file
          open-output-file open-binary-output-file
          call-with-input-file call-with-output-file
          with-input-from-file with-output-to-file))
"),
    },
    // scheme/repl: VFS shadow — sandboxed contexts get neutered interaction-environment.
    // returns (current-environment) = the sandbox's restricted env.
    // full sandboxed eval/repl tracked in GH issue #97.
    VfsEntry {
        path: "scheme/repl",
        deps: &[],
        files: &[],
        clib: None,
        default_safe: true,
        source: VfsSource::Shadow,
        feature: None,
        shadow_sld: Some("\
(define-library (scheme repl)
  (import (chibi))
  (export interaction-environment)
  (begin
    (define (interaction-environment) (current-environment))))
"),
    },
    // scheme/process-context: VFS shadow — re-exports from (tein process).
    // trampolines neuter env vars, command-line in sandboxed contexts.
    // exit uses (tein process) eval escape hatch; emergency-exit aliases exit.
    VfsEntry {
        path: "scheme/process-context",
        deps: &["tein/process"],
        files: &[],
        clib: None,
        default_safe: true,
        source: VfsSource::Shadow,
        feature: None,
        shadow_sld: Some("\
(define-library (scheme process-context)
  (import (tein process))
  (export get-environment-variable get-environment-variables
          command-line exit emergency-exit)
  (begin
    (define emergency-exit exit)))
"),
    },
    // scheme/time: default_safe: false — depends on scheme/process-context + scheme/file
    VfsEntry {
        path: "scheme/time",
        deps: &["scheme/time/tai", "scheme/time/tai-to-utc-offset"],
        files: &["lib/scheme/time.sld"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/time/tai",
        deps: &["scheme/base", "scheme/time/tai-to-utc-offset"],
        files: &["lib/scheme/time/tai.sld"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/time/tai-to-utc-offset",
        deps: &["scheme/base", "scheme/read", "srfi/18"],
        files: &["lib/scheme/time/tai-to-utc-offset.sld"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // scheme/show: deps satisfied via shadows — scheme/file via (tein file),
    // scheme/repl via (current-environment)
    VfsEntry {
        path: "scheme/show",
        deps: &["srfi/166"],
        files: &["lib/scheme/show.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "scheme/mapping/hash",
        deps: &["srfi/146/hash"],
        files: &["lib/scheme/mapping/hash.sld"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // -------------------------------------------------------------------------
    // srfi modules
    // -------------------------------------------------------------------------
    VfsEntry {
        path: "srfi/1",
        deps: &[],
        files: &[
            "lib/srfi/1.sld",
            "lib/srfi/1/predicates.scm",
            "lib/srfi/1/selectors.scm",
            "lib/srfi/1/search.scm",
            "lib/srfi/1/misc.scm",
            "lib/srfi/1/constructors.scm",
            "lib/srfi/1/fold.scm",
            "lib/srfi/1/deletion.scm",
            "lib/srfi/1/alists.scm",
            "lib/srfi/1/lset.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/1/immutable",
        deps: &[],
        files: &[
            "lib/srfi/1/immutable.sld",
            "lib/srfi/1/predicates.scm",
            "lib/srfi/1/selectors.scm",
            "lib/srfi/1/search.scm",
            "lib/srfi/1/misc.scm",
            "lib/srfi/1/constructors.scm",
            "lib/srfi/1/fold.scm",
            "lib/srfi/1/deletion.scm",
            "lib/srfi/1/alists.scm",
            "lib/srfi/1/lset.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/2",
        deps: &[],
        files: &["lib/srfi/2.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/8",
        deps: &[],
        files: &["lib/srfi/8.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/9",
        deps: &[],
        files: &["lib/srfi/9.sld", "lib/srfi/9.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/11",
        deps: &[],
        files: &["lib/srfi/11.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/14",
        deps: &["chibi/char-set"],
        files: &["lib/srfi/14.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/16",
        deps: &[],
        files: &["lib/srfi/16.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/18",
        deps: &["srfi/9", "chibi/ast", "chibi/time"],
        files: &[
            "lib/srfi/18.sld",
            "lib/srfi/18/types.scm",
            "lib/srfi/18/interface.scm",
        ],
        clib: Some(ClibEntry {
            source: "lib/srfi/18/threads.c",
            init_suffix: "srfi_18_threads",
            vfs_key: "/vfs/lib/srfi/18/threads",
            // threads.c uses <sys/time.h>, <poll.h>, <unistd.h> — posix-only
            posix_only: true,
        }),
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/27",
        deps: &[],
        files: &["lib/srfi/27.sld", "lib/srfi/27/constructors.scm"],
        clib: Some(ClibEntry {
            source: "lib/srfi/27/rand.c",
            init_suffix: "srfi_27_rand",
            vfs_key: "/vfs/lib/srfi/27/rand",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/38",
        deps: &["srfi/69", "chibi/ast"],
        files: &["lib/srfi/38.sld", "lib/srfi/38.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/39",
        deps: &[],
        files: &[
            "lib/srfi/39.sld",
            "lib/srfi/39/syntax.scm",
            "lib/srfi/39/syntax-no-threads.scm",
        ],
        clib: Some(ClibEntry {
            source: "lib/srfi/39/param.c",
            init_suffix: "srfi_39_param",
            vfs_key: "/vfs/lib/srfi/39/param",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/41",
        deps: &["scheme/base", "scheme/lazy", "srfi/1"],
        files: &["lib/srfi/41.sld", "lib/srfi/41.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/69",
        deps: &["srfi/9"],
        files: &[
            "lib/srfi/69.sld",
            "lib/srfi/69/type.scm",
            "lib/srfi/69/interface.scm",
        ],
        clib: Some(ClibEntry {
            source: "lib/srfi/69/hash.c",
            init_suffix: "srfi_69_hash",
            vfs_key: "/vfs/lib/srfi/69/hash",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/95",
        deps: &[],
        files: &["lib/srfi/95.sld", "lib/srfi/95/sort.scm"],
        clib: Some(ClibEntry {
            source: "lib/srfi/95/qsort.c",
            init_suffix: "srfi_95_qsort",
            vfs_key: "/vfs/lib/srfi/95/qsort",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // srfi/98: env var access. clib for unsandboxed; shadow neuters in sandbox.
    // needed by srfi/128 (hash salt) in the (scheme show) dep chain.
    // two entries: Embedded (C clib, unsandboxed) + Shadow (neutered stubs, sandboxed).
    VfsEntry {
        path: "srfi/98",
        deps: &[],
        files: &["lib/srfi/98.sld"],
        clib: Some(ClibEntry {
            source: "lib/srfi/98/env.c",
            init_suffix: "srfi_98_env",
            vfs_key: "/vfs/lib/srfi/98/env",
            posix_only: false,
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // srfi/98: VFS shadow — sandboxed contexts get neutered env var stubs.
    // get-environment-variable always returns #f; get-environment-variables returns '().
    VfsEntry {
        path: "srfi/98",
        deps: &[],
        files: &[],
        clib: None,
        default_safe: true,
        source: VfsSource::Shadow,
        feature: None,
        shadow_sld: Some("\
(define-library (srfi 98)
  (import (scheme base))
  (export get-environment-variable get-environment-variables)
  (begin
    (define (get-environment-variable name) #f)
    (define (get-environment-variables) '())))
"),
    },
    VfsEntry {
        path: "srfi/101",
        deps: &["scheme/base", "srfi/16", "srfi/1", "srfi/125", "srfi/151"],
        files: &["lib/srfi/101.sld", "lib/srfi/101.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/111",
        deps: &["scheme/base"],
        files: &["lib/srfi/111.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/113",
        deps: &["scheme/base", "srfi/1", "srfi/125", "srfi/128"],
        files: &[
            "lib/srfi/113.sld",
            "lib/srfi/113/sets.scm",
            "lib/srfi/113/bags.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/115",
        deps: &["chibi/regexp"],
        files: &["lib/srfi/115.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/116",
        deps: &["scheme/base", "srfi/1/immutable", "srfi/128"],
        files: &["lib/srfi/116.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/117",
        deps: &["scheme/base", "srfi/1"],
        files: &["lib/srfi/117.sld", "lib/srfi/117/queue.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/121",
        deps: &["scheme/base", "srfi/130"],
        files: &["lib/srfi/121.sld", "lib/srfi/121/generators.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/124",
        deps: &["chibi/weak", "scheme/base"],
        files: &["lib/srfi/124.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/125",
        deps: &["scheme/base", "srfi/128", "srfi/69", "chibi/ast"],
        files: &["lib/srfi/125.sld", "lib/srfi/125/hash.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/127",
        deps: &["scheme/base", "srfi/1"],
        files: &["lib/srfi/127.sld", "lib/srfi/127.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/128",
        deps: &[
            "scheme/base",
            "scheme/char",
            "srfi/27",
            "srfi/69",
            "srfi/95",
            "srfi/98",
            "srfi/151",
            "chibi/ast",
        ],
        files: &[
            "lib/srfi/128.sld",
            "lib/srfi/128/comparators.scm",
            "lib/srfi/128/162-impl.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/130",
        deps: &["scheme/base", "scheme/char", "scheme/write", "chibi/string"],
        files: &["lib/srfi/130.sld", "lib/srfi/130.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/132",
        deps: &["scheme/base", "srfi/95"],
        files: &["lib/srfi/132.sld", "lib/srfi/132/sort.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/133",
        deps: &["scheme/base"],
        files: &["lib/srfi/133.sld", "lib/srfi/133/vector.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/134",
        deps: &["scheme/base", "srfi/16", "srfi/1", "srfi/9", "srfi/121"],
        files: &["lib/srfi/134.sld", "lib/srfi/134.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/135",
        deps: &["scheme/base", "srfi/16", "scheme/char", "srfi/135/kernel8"],
        files: &["lib/srfi/135.sld", "lib/srfi/135.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/135/kernel8",
        deps: &["scheme/base"],
        files: &["lib/srfi/135/kernel8.sld", "lib/srfi/135/kernel8.body.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/141",
        deps: &["scheme/base", "scheme/division"],
        files: &["lib/srfi/141.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/143",
        deps: &["scheme/base", "srfi/141", "srfi/151"],
        files: &["lib/srfi/143.sld", "lib/srfi/143/fixnum.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/144",
        deps: &["srfi/141"],
        files: &["lib/srfi/144.sld", "lib/srfi/144/flonum.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/145",
        deps: &["scheme/base", "chibi/assert"],
        files: &["lib/srfi/145.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/146",
        deps: &[
            "scheme/base",
            "srfi/16",
            "srfi/1",
            "srfi/2",
            "srfi/8",
            "srfi/121",
            "srfi/128",
            "srfi/145",
        ],
        files: &[
            "lib/srfi/146.sld",
            "lib/srfi/146/rbtree.scm",
            "lib/srfi/146/mapping.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/146/hamt",
        deps: &[
            "scheme/base",
            "srfi/16",
            "srfi/143",
            "srfi/151",
            "srfi/146/hamt-misc",
            "srfi/146/vector-edit",
        ],
        files: &["lib/srfi/146/hamt.sld", "lib/srfi/146/hamt.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/146/hamt-map",
        deps: &[
            "scheme/base",
            "srfi/16",
            "srfi/1",
            "srfi/146/hamt",
            "srfi/146/hamt-misc",
        ],
        files: &["lib/srfi/146/hamt-map.sld", "lib/srfi/146/hamt-map.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/146/hamt-misc",
        deps: &["scheme/base", "srfi/16", "srfi/125", "srfi/128"],
        files: &["lib/srfi/146/hamt-misc.sld", "lib/srfi/146/hamt-misc.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/146/vector-edit",
        deps: &["scheme/base"],
        files: &[
            "lib/srfi/146/vector-edit.sld",
            "lib/srfi/146/vector-edit.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/146/hash",
        deps: &[
            "scheme/base",
            "srfi/16",
            "srfi/1",
            "srfi/8",
            "srfi/121",
            "srfi/128",
            "srfi/145",
            "srfi/146/hamt-map",
        ],
        files: &["lib/srfi/146/hash.sld", "lib/srfi/146/hash.scm"],
        clib: None,
        default_safe: false,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/151",
        deps: &[],
        files: &["lib/srfi/151.sld", "lib/srfi/151/bitwise.scm"],
        clib: Some(ClibEntry {
            source: "lib/srfi/151/bit.c",
            init_suffix: "srfi_151_bit",
            posix_only: false,
            vfs_key: "/vfs/lib/srfi/151/bit",
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/165",
        deps: &[
            "scheme/base",
            "srfi/1",
            "srfi/111",
            "srfi/125",
            "srfi/128",
            "srfi/146",
        ],
        files: &["lib/srfi/165.sld", "lib/srfi/165.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/166",
        deps: &[
            "srfi/166/base",
            "srfi/166/pretty",
            "srfi/166/columnar",
            "srfi/166/unicode",
            "srfi/166/color",
        ],
        files: &["lib/srfi/166.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // scheme/repl dep satisfied via VFS shadow (neutered interaction-environment)
    VfsEntry {
        path: "srfi/166/base",
        deps: &[
            "scheme/base",
            "scheme/char",
            "scheme/complex",
            "scheme/inexact",
            "scheme/repl",
            "scheme/write",
            "srfi/1",
            "srfi/69",
            "srfi/130",
            "srfi/165",
            "chibi/show/shared",
        ],
        files: &[
            "lib/srfi/166/base.sld",
            "lib/srfi/166/base.scm",
            "lib/srfi/166/write.scm",
            "lib/srfi/166/show.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/166/pretty",
        deps: &[
            "scheme/base",
            "scheme/char",
            "scheme/write",
            "chibi/show/shared",
            "srfi/1",
            "srfi/69",
            "srfi/130",
            "srfi/166/base",
            "srfi/166/color",
        ],
        files: &["lib/srfi/166/pretty.sld", "lib/srfi/166/pretty.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/166/columnar",
        deps: &[
            "scheme/base",
            "scheme/char",
            "scheme/file",   // shadow — resolves via (tein file) in sandbox
            "srfi/1",
            "srfi/117",
            "srfi/130",
            "srfi/166/base",
            "chibi/optional",
        ],
        files: &["lib/srfi/166/columnar.sld", "lib/srfi/166/column.scm"],
        clib: None,
        // scheme/file dep satisfied via VFS shadow → (tein file)
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/166/unicode",
        deps: &[
            "scheme/base",
            "scheme/char",
            "srfi/130",
            "srfi/151",
            "srfi/166/base",
        ],
        files: &[
            "lib/srfi/166/unicode.sld",
            "lib/srfi/166/width.scm",
            "lib/srfi/166/unicode.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "srfi/166/color",
        deps: &["scheme/base", "srfi/130", "srfi/166/base"],
        files: &["lib/srfi/166/color.sld", "lib/srfi/166/color.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    // -------------------------------------------------------------------------
    // chibi internal modules (transitive deps)
    // -------------------------------------------------------------------------
    VfsEntry {
        path: "chibi/ast",
        deps: &[],
        files: &["lib/chibi/ast.sld", "lib/chibi/ast.scm"],
        clib: Some(ClibEntry {
            source: "lib/chibi/ast.c",
            init_suffix: "chibi_ast",
            posix_only: false,
            vfs_key: "/vfs/lib/chibi/ast",
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/assert",
        deps: &[],
        files: &["lib/chibi/assert.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/equiv",
        deps: &["srfi/69"],
        files: &["lib/chibi/equiv.sld", "lib/chibi/equiv.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/io",
        deps: &["chibi/ast"],
        files: &["lib/chibi/io.sld", "lib/chibi/io/io.scm"],
        clib: Some(ClibEntry {
            source: "lib/chibi/io/io.c",
            init_suffix: "chibi_io",
            posix_only: false,
            vfs_key: "/vfs/lib/chibi/io/io",
        }),
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/optional",
        deps: &[],
        files: &["lib/chibi/optional.sld", "lib/chibi/optional.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/string",
        deps: &["chibi/ast", "chibi/char-set/base"],
        files: &["lib/chibi/string.sld", "lib/chibi/string.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/weak",
        deps: &[],
        files: &["lib/chibi/weak.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/time",
        deps: &[],
        files: &["lib/chibi/time.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/char-set",
        deps: &["chibi/char-set/base", "chibi/char-set/extras"],
        files: &["lib/chibi/char-set.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/char-set/base",
        deps: &["chibi/iset/base"],
        files: &["lib/chibi/char-set/base.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/char-set/full",
        deps: &["chibi/iset/base", "chibi/char-set/base"],
        files: &["lib/chibi/char-set/full.sld", "lib/chibi/char-set/full.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/char-set/ascii",
        deps: &["chibi/iset/base", "chibi/char-set/base"],
        files: &[
            "lib/chibi/char-set/ascii.sld",
            "lib/chibi/char-set/ascii.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/char-set/extras",
        deps: &["chibi/iset", "chibi/char-set/base"],
        files: &[
            "lib/chibi/char-set/extras.sld",
            "lib/chibi/char-set/extras.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/char-set/boundary",
        deps: &["chibi/char-set"],
        files: &[
            "lib/chibi/char-set/boundary.sld",
            "lib/chibi/char-set/boundary.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/iset",
        deps: &[
            "scheme/base",
            "chibi/iset/base",
            "chibi/iset/iterators",
            "chibi/iset/constructors",
        ],
        files: &["lib/chibi/iset.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/iset/base",
        deps: &["srfi/9", "srfi/151"],
        files: &["lib/chibi/iset/base.sld", "lib/chibi/iset/base.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/iset/iterators",
        deps: &["chibi/iset/base", "srfi/9", "srfi/151"],
        files: &[
            "lib/chibi/iset/iterators.sld",
            "lib/chibi/iset/iterators.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/iset/constructors",
        deps: &["chibi/iset/base", "chibi/iset/iterators", "srfi/151"],
        files: &[
            "lib/chibi/iset/constructors.sld",
            "lib/chibi/iset/constructors.scm",
        ],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/regexp",
        deps: &[
            "srfi/69",
            "scheme/char",
            "srfi/9",
            "chibi/char-set",
            "chibi/char-set/full",
            "chibi/char-set/ascii",
            "srfi/151",
            "chibi/char-set/boundary",
        ],
        files: &["lib/chibi/regexp.sld", "lib/chibi/regexp.scm"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
    VfsEntry {
        path: "chibi/show/shared",
        deps: &["scheme/base", "scheme/write", "srfi/69"],
        files: &["lib/chibi/show/shared.sld"],
        clib: None,
        default_safe: true,
        source: VfsSource::Embedded,
        feature: None,
        shadow_sld: None,
    },
];
